# Generated by Django 5.2 on 2025-11-30 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='股票代码', max_length=10, unique=True)),
                ('name', models.CharField(help_text='股票名称', max_length=100)),
                ('industry', models.CharField(blank=True, help_text='所属行业', max_length=50, null=True)),
                ('sector', models.CharField(blank=True, help_text='所属板块', max_length=50, null=True)),
                ('listing_date', models.DateField(blank=True, help_text='上市日期', null=True)),
                ('market', models.CharField(choices=[('SH', '沪市'), ('SZ', '深市')], help_text='交易市场', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='是否仍在交易')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('quarterly', '季度报告'), ('annual', '年度报告')], help_text='报告类型', max_length=10)),
                ('report_date', models.DateField(help_text='报告期')),
                ('announcement_date', models.DateField(help_text='公告日期')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, help_text='营业收入', max_digits=15, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, help_text='净利润', max_digits=15, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, help_text='总资产', max_digits=15, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, help_text='总负债', max_digits=15, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, help_text='股东权益', max_digits=15, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=4, help_text='每股收益', max_digits=10, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=4, help_text='净资产收益率', max_digits=10, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to='market_data.stock')),
            ],
            options={
                'unique_together': {('stock', 'report_type', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='交易日期')),
                ('open_price', models.DecimalField(decimal_places=2, help_text='开盘价', max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, help_text='最高价', max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, help_text='最低价', max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, help_text='收盘价', max_digits=10)),
                ('volume', models.BigIntegerField(help_text='成交量')),
                ('turnover', models.DecimalField(decimal_places=2, help_text='成交额', max_digits=15)),
                ('adjusted_close', models.DecimalField(decimal_places=2, help_text='复权收盘价', max_digits=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='market_data.stock')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
